import { useState, useEffect } from "react";
import { Link } from "react-router-dom";
import api from "../services/api";

export default function ForgotPassword() {
  // Always scroll to top
  useEffect(() => {
    window.scrollTo({ top: 0, left: 0, behavior: "smooth" });
  }, []);

  const [email, setEmail] = useState("");
  const [loading, setLoading] = useState(false);
  const [isSent, setIsSent] = useState(false);
  const [demoLink, setDemoLink] = useState(""); 
  
  // 🟢 VALIDATION ERRORS STATE
  const [errors, setErrors] = useState({});
  const [toast, setToast] = useState({ show: false, message: "", type: "error" });

  const showToast = (message, type = "error") => {
    setToast({ show: true, message, type });
  };

  useEffect(() => {
    if (toast.show) {
      const timer = setTimeout(() => setToast({ ...toast, show: false }), 4000);
      return () => clearTimeout(timer);
    }
  }, [toast.show]);

  // 🟢 STRICT INLINE VALIDATION
  const validateForm = () => {
    let newErrors = {};
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

    if (!email.trim()) {
      newErrors.email = "Email is required.";
    } else if (!emailRegex.test(email)) {
      newErrors.email = "Please enter a valid email address.";
    }

    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!validateForm()) return;

    try {
      setLoading(true);
      const res = await api.post("/auth/forgot-password", { email });
      
      showToast(res.data.message, "success");
      setIsSent(true);

      // FOR DEMO: Capture the link generated by the backend
      if (res.data.demoLink) {
        setDemoLink(res.data.demoLink);
      }
      
    } catch (error) {
      showToast(error.response?.data?.message || "Something went wrong.", "error");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="bg-neutral-50 min-h-[100dvh] flex flex-col items-center justify-center font-sans px-6 relative selection:bg-neutral-200 overflow-hidden">
      
      {/* 🟢 TOAST NOTIFICATION */}
      <div 
        className={`fixed left-1/2 top-8 z-[100] flex w-[90%] max-w-sm -translate-x-1/2 transform items-center gap-2.5 rounded-sm p-3 shadow-[0_20px_50px_-10px_rgba(0,0,0,0.15)] backdrop-blur-xl transition-all duration-500 ease-[0.25,1,0.5,1] ${
          toast.show ? "translate-y-0 opacity-100" : "-translate-y-10 opacity-0 pointer-events-none"
        } ${toast.type === "error" ? "bg-white/95 border-l-3 border-red-500 text-neutral-800" : "bg-neutral-950/95 text-white"}`}
      >
        <p className={`text-[10px] font-medium tracking-wide ${toast.type === "error" ? "text-neutral-700" : "text-neutral-200"}`}>
          {toast.message}
        </p>
      </div>

      <div className="w-full max-w-[340px] bg-white p-8 shadow-xl border border-neutral-100 my-auto">
        
        <Link to="/login" className="inline-flex items-center gap-1.5 text-[9px] font-bold uppercase tracking-[0.2em] text-neutral-400 hover:text-neutral-900 transition-colors mb-6">
          <svg className="h-3.5 w-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
            <path strokeLinecap="round" strokeLinejoin="round" d="M10 19l-7-7m0 0l7-7m-7 7h18" />
          </svg>
          Back to Login
        </Link>

        <div className="mb-6">
          <h1 className="text-2xl font-light tracking-wide uppercase text-neutral-900 mb-1.5">
            Reset Password
          </h1>
          <p className="text-[9px] font-bold tracking-[0.2em] uppercase text-neutral-400 leading-relaxed">
            Enter your email to receive recovery instructions.
          </p>
        </div>

        {!isSent ? (
          <form onSubmit={handleSubmit} className="space-y-5" noValidate>
            
            {/* EMAIL INPUT WITH VALIDATION */}
            <div className="relative group pt-1">
              <input 
                type="email" id="email" placeholder=" " value={email} 
                onChange={(e) => { setEmail(e.target.value); setErrors({...errors, email: ""}); }} 
                required 
                className={`peer block w-full rounded-none border-b bg-transparent px-0 py-2 text-xs font-light text-neutral-900 transition-all focus:outline-none focus:ring-0 ${errors.email ? 'border-red-500 focus:border-red-500' : 'border-neutral-300 focus:border-neutral-900'}`}
              />
              <label 
                htmlFor="email" 
                className={`absolute left-0 top-2 text-[9px] font-bold uppercase tracking-[0.2em] transition-all duration-300 peer-focus:-translate-y-5 peer-focus:text-[7.5px] peer-[:not(:placeholder-shown)]:-translate-y-5 peer-[:not(:placeholder-shown)]:text-[7.5px] ${errors.email ? 'text-red-500 peer-focus:text-red-500' : 'text-neutral-400 peer-focus:text-neutral-900'}`}
              >
                Email Address
              </label>
              {errors.email && <span className="text-red-500 text-[8px] font-bold uppercase tracking-wider block mt-1.5">{errors.email}</span>}
            </div>

            <button 
              type="submit" disabled={loading}
              className={`mt-8 relative w-full flex items-center justify-center px-4 py-3.5 text-[9px] font-bold tracking-[0.25em] uppercase text-white transition-all active:scale-[0.98] ${
                loading ? "bg-neutral-400 cursor-not-allowed" : "bg-neutral-950 hover:bg-neutral-800"
              }`}
            >
              {loading ? "Sending..." : "Send Recovery Link"}
            </button>
          </form>
        ) : (
          <div className="text-center animate-fade-in">
            <div className="w-12 h-12 bg-emerald-50 text-emerald-500 rounded-full flex items-center justify-center mx-auto mb-4">
               <svg className="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}><path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" /></svg>
            </div>
            <p className="text-xs text-neutral-600 font-light mb-6">If an account exists for <span className="font-medium text-neutral-900">{email}</span>, a recovery link has been generated.</p>
            
            {/* 🟢 DEMO BYPASS: Show link directly for local testing without email setup */}
            {demoLink && (
              <div className="bg-neutral-100 p-4 border border-neutral-200 mt-6">
                <p className="text-[8px] font-bold tracking-widest uppercase text-neutral-500 mb-2">Development Mode bypass</p>
                <a href={demoLink} className="text-[10px] text-neutral-900 font-bold uppercase underline break-all">Click here to reset</a>
              </div>
            )}
          </div>
        )}

      </div>
    </div>
  );
}